In [1]:
import numpy as np
z = np.arange(0.5, 10, 2.1)
z

array([0.5, 2.6, 4.7, 6.8, 8.9])

In [2]:
z.shape

(5,)

In [4]:
z = np.arange(0.5, 12, 2.1)
z

array([ 0.5,  2.6,  4.7,  6.8,  8.9, 11. ])

In [5]:
z.shape

(6,)

In [6]:
np.linspace(0,4,9, endpoint = False)

array([0.        , 0.44444444, 0.88888889, 1.33333333, 1.77777778,
       2.22222222, 2.66666667, 3.11111111, 3.55555556])

In [7]:
np.linspace(0,4,9)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [9]:
a = np.array([1, 2, 'day', 5, 'year', 7, 0, 0, 'month'])

In [10]:
a[2:5]

array(['day', '5', 'year'], dtype='<U21')

In [11]:
a[1:6:2]

array(['2', '5', '7'], dtype='<U21')

In [13]:
M = np.array([[1, 2], [0, -1]])
M

array([[ 1,  2],
       [ 0, -1]])

In [16]:
M.shape # you can also use np.shape(M)

(2, 2)

In [17]:
M[-1]

array([ 0, -1])

In [18]:
M[1:]

array([[ 0, -1]])

In [27]:
a = np.array([[1,2,-2],[0,3,1],[-1,-1,0]])
a.reshape(1,9)
a

array([[ 1,  2, -2],
       [ 0,  3,  1],
       [-1, -1,  0]])

In [20]:
d = np.arange(21)
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [21]:
d.shape

(21,)

In [22]:
d.shape = 3,7
d

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20]])

In [23]:
d.shape = 7,3
d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [26]:
d.shape = 21, 1
d

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20]])

In [29]:
D = np.diag([1,1,1])
D

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [30]:
c = np.array([0, 1, 8, 27, 64])
c

array([ 0,  1,  8, 27, 64])

In [31]:
c.astype('complex')

array([ 0.+0.j,  1.+0.j,  8.+0.j, 27.+0.j, 64.+0.j])

In [35]:
a = np.array([[1,-2,2],[0,3,1],[-1,-1,0]], dtype = float)
a

array([[ 1., -2.,  2.],
       [ 0.,  3.,  1.],
       [-1., -1.,  0.]])

In [39]:
a[0:2]

array([[ 1., -2.,  2.],
       [ 0.,  3.,  1.]])

In [40]:
a[0:3:2]

array([[ 1., -2.,  2.],
       [-1., -1.,  0.]])

In [42]:
a[:,0]

array([ 1.,  0., -1.])

In [51]:
a[:,0:3] # gives from the first row to the last

array([[ 1., -2.,  2.],
       [ 0.,  3.,  1.],
       [-1., -1.,  0.]])

In [49]:
a[:,1:3] #gives the second and last row

array([[-2.,  2.],
       [ 3.,  1.],
       [-1.,  0.]])

In [54]:
a[:,0:3:2] #gives the first and last row

array([[ 1.,  2.],
       [ 0.,  1.],
       [-1.,  0.]])

In [55]:
a[0,0]

1.0

In [56]:
a[0,2]

2.0

In [57]:
a[1,1]

3.0

In [58]:
a[2,1]

-1.0

In [1]:
print(list('I am fine at AIMS'))

['I', ' ', 'a', 'm', ' ', 'f', 'i', 'n', 'e', ' ', 'a', 't', ' ', 'A', 'I', 'M', 'S']


In [3]:
import numpy as np
x = np.array([-2, 1, 0, 1, 2, 3])
q = np.where(x>0, 2*x, 1-x)
q

array([3, 2, 1, 2, 4, 6])

In [5]:
V = np.array([-2, 1, 0, 1, 2, 3])
def w(x):
    if x > 0:
        return 2*x
    else:
        return 1 - x
q = np.vectorize(w)
q(V)

array([3, 2, 1, 2, 4, 6])

In [6]:
A = np.array([1, 2, 3, 4])
A

array([1, 2, 3, 4])

In [7]:
A[1] = 7
A

array([1, 7, 3, 4])

In [8]:
B = np.array([[1, -2],[3, 7], [-1, 5]])
B

array([[ 1, -2],
       [ 3,  7],
       [-1,  5]])

In [10]:
B[1:3] = 7,6
B

array([[ 1, -2],
       [ 7,  6],
       [ 7,  6]])

In [16]:
A = np.array([[1, -2],[3, 7], [-1, 5],[2,8]])
A

array([[ 1, -2],
       [ 3,  7],
       [-1,  5],
       [ 2,  8]])

In [15]:
print('Dimensions:', A.ndim)
print('Shape:', A.shape)
print('Size:', A.size)

Dimensions: 2
Shape: (4, 2)
Size: 8


In [20]:
M = np.zeros((10,10))
M
for i in range(10):
    for j in range(10):
        if i == j:
            M[i,j] = 2
        elif abs(j - i) == 1:
            M[i,j] = -1
M
        

array([[ 2., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-1.,  2., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., -1.,  2., -1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., -1.,  2., -1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -1.,  2., -1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., -1.,  2., -1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., -1.,  2., -1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0., -1.,  2., -1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  2., -1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  2.]])

In [24]:
# 1 below the diagonal and -1 above it
M = np.zeros((10,10))
M
for i in range(10):
    for j in range(10):
        if i == j:
            M[i,j] = 2
        elif j - i == 1:
            M[i,j] = -1
        elif j - i == -1:
            M[i,j] = 1
M
    

array([[ 2., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  2., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  2., -1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  2., -1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  2., -1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  2., -1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  2., -1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  2., -1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  2., -1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  2.]])

In [27]:
M = np.zeros((10,10))
M
for i in range(10):
    for j in range(10):
        if i == j:
            M[i,j] = 2
        elif j - i == 1:
            M[i,j] = -1
        elif j - i == -1:
            M[i,j] = 1
        else:
            M[i,j] = 6
M

array([[ 2., -1.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 1.,  2., -1.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 6.,  1.,  2., -1.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 6.,  6.,  1.,  2., -1.,  6.,  6.,  6.,  6.,  6.],
       [ 6.,  6.,  6.,  1.,  2., -1.,  6.,  6.,  6.,  6.],
       [ 6.,  6.,  6.,  6.,  1.,  2., -1.,  6.,  6.,  6.],
       [ 6.,  6.,  6.,  6.,  6.,  1.,  2., -1.,  6.,  6.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  1.,  2., -1.,  6.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  1.,  2., -1.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  1.,  2.]])

In [29]:
a = np.array([-4,-2])
b = np.array([2,5]) # you can also use np.dot(a,b)
a@b

-18

In [35]:
m = np.array([[1,2],[3,4]])
n = np.array([[1,2],[2,1]])
print(m)
print('================')
print(n)


[[1 2]
 [3 4]]
[[1 2]
 [2 1]]


In [33]:
m@n

array([[ 5,  4],
       [11, 10]])

In [34]:
n@m

array([[ 7, 10],
       [ 5,  8]])

In [36]:
print(a)
print('=================')
print(m)

[-4 -2]
[[1 2]
 [3 4]]


In [37]:
print(np.dot(m,a))

[ -8 -20]


In [38]:
print(np.multiply(m,n)) #component-wise multiplication

[[1 4]
 [6 4]]


In [39]:
print(m)
print('============')
print(np.diagonal(m))

[[1 2]
 [3 4]]
[1 4]


In [40]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [41]:
print(np.trace(m))

5


In [51]:
# 2I + 
R = np.array([[1, 3], [-1, 7]])
S = np.array([[5, 2], [1, 2]])
I = np.diag([1,1])
print(R)
print('=======')
print(S)
print('========')
print(I)
print('=======')
print(2*I + 4*R + R@S) #note to self: when multiplying a matrix by a matrix, always use "@" between the two matrices

[[ 1  3]
 [-1  7]]
[[5 2]
 [1 2]]
[[1 0]
 [0 1]]
[[14 20]
 [-2 42]]
